### ISSUE TITLE
Segfault when using options with Makeflow

### ISSUE THREAD

**Issue by ajmazurie** [cooperative-computing-lab/cctools#692]
Hi,
I am currently using the pre-compiled cctools binaries for OSX 10.9 (`cctools-4.3.2-x86_64-osx-10.9.tar.gz`), and have the following behavior:

```shell
> makeflow test.makeflow
     Total rules: 1
Starting execution of workflow: test.makeflow.
nothing left to do.
> makeflow test.makeflow -f test.log
zsh: segmentation fault  makeflow test.makeflow -f test.log
```

I get the same behavior with the `--makeflow-log` option. Any idea about what's causing this? I confirm that I can replicate this issue with a compiled version of the code on a Linux box.

Aurelien

**Comment by btovar** [comment]
Aurelien,

Thanks for the report. @charleszheng44, can you reproduce this on a linux machine, or is this only an issue with OSX?

**Comment by dthain** [comment]
@hmeng-19 and @charleszheng44,  A segfault at startup in makeflow is a very high priority bug, please work together to figure out the problem.  If the problem also appears on Linux, it may be easier to find there.

**Comment by btovar** [comment]
Fixed on master with: df230c0e26494a0c73930a62a5bdc0b5d1e2eafc
Fixed on release 4.3.3.

**Comment by batrick** [comment]
Not quite fixed. The long option is using `no_argument`:

`{"summary-log", no_argument, 0, 'f'},`

when it should be using `required_argument`.

**Comment by btovar** [comment]
Thanks Patrick.
